Правки + 8.1 задание
htmlacademy-javascript/1305635-keksobooking-22 pull request #10
Opened 2021-03-13 14:42 UTC by DaryaV95

2021-03-13 16:00 UTC, anastasiiayeromina commented on js/filter.js
> +import {mapFilters} from './disable-form.js';
Мне не нравится, что мы получаем элементы из других модулей, не предназначенных специально для получения элементов, это порождает зависимости между модулями. А лучше, чтобы модули были как можно более независимы.
Поэтому предлагаю создать отдельный модуль (например, elements.js), который будет отвечать за то, чтобы получать все нужные dom-элементы нашего приложения через querySelector.
И уже из модуля elements.js импортировать нужные элементы во все осталльные модули приложения.

2021-03-13 22:38 UTC, anastasiiayeromina requested changes

2021-03-13 22:38 UTC, anastasiiayeromina commented on js/filter.js
> +    if (data.indexOf(feature.value) === -1) {
В этой строке теперь нужно вместо `data` использовать `data.offer.features` по аналогии с другими фильтрами :)

2021-03-14 07:53 UTC, DaryaV95 commented on js/filter.js
> +    if (data.indexOf(feature.value) === -1) {
поправила

2021-03-14 11:13 UTC, anastasiiayeromina approved these changes

2021-03-14 11:13 UTC, merged